customer:
  property: Gateway Profile Dev

#Application Configuration
server:
  error:
    include-message: always
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**
  
  output:
    ansi:
      enabled: always
